apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "redis-api.name" . }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage.size }}
